name: Store Bug Reports in Project

on:
  issues:
    types: [opened]

jobs:
  store-in-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is a Bug Report
        id: check_bug_report
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const template = /<!--\s*Bug Report\s*-->/i;
            const isBugReport = template.test(issue.body);
            return { isBugReport };

      - name: Add issue to project
        if: steps.check_bug_report.outputs.isBugReport
        uses: peter-evans/create-issue-comment@v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This issue has been added to the Bug Report project.
          issue-number: ${{ github.event.issue.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: https://github.com/orgs/gezelio/projects/6
          column-name: To do