name: Add Suggestions to project

on:
  issues:
    types:
      - labeled
      - unlabeled

concurrency:
  group: update-projects-${{ github.event_name }}
  cancel-in-progress: true


jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      # substitute RELEASE_VERSION for the latest version available in releases
      - uses: Machine-Maker/add-to-project-action@v0.2.0
        with:
          github-token: ${{ secrets.TOKEN }}
          project-url: https://github.com/orgs/gezelio/projects/5/views/1 # e.g. https://github.com/users/Machine-Maker/projects/1/views/1
          column-field: Status
          label-to-column-map: |
            {
              "Suggestions": "Suggestions",
              "Bug": "User Reported Bugs"
            }
