name: Create PR comment

on:
  pull_request:
    types: [opened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.0.0-rc.1'
      - name: Install dependencies
        run: npm install
      - name: Create comment
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;
            const comment = `Thanks for opening this pull request! Here's a checklist to help ensure everything is up to date:\n\n- [ ] Update the extension file\n- [ ] Double check the readme is complete\n- [ ] Update the extension to open a new page on this new release\n\nPlease check off each item as you complete it.`;
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            const { data: comments } = await octokit.issues.listComments({
              owner,
              repo,
              issue_number: number
            });
            const existingComment = comments.find(comment => comment.body === comment);
            if (!existingComment) {
              await octokit.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: comment
              });
            }