name: Sync README

on:
  push:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync README
        run: |
          cp README.md docs/README.md
          git add docs/README.md
          git commit -m "Sync README.md"
          git push