name: Sync README

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync README
        if: github.event.head_commit.modified || contains('README.md')
        run: |
          cp README.md docs/README.md
          git add docs/README.md
          git commit -m "Sync README.md"
          git push