name: Sync README

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync README
        if: steps.check_readme.outputs.modified == 'true'
        id: check_readme
        run: echo "::set-output name=modified::$(if [ -n "$(git diff --name-only HEAD^ HEAD | grep README.md)" ]; then echo 'true'; else echo 'false'; fi)"

      - name: Copy README
        if: steps.check_readme.outputs.modified == 'true'
        run: |
          cp README.md docs/README.md
          git add docs/README.md
          git commit -m "Sync README.md"
          git push