name: Releases

on:
  push:
    paths:
      - 'streamerbot/YTCR.v.*.*.*.gezel'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print head_commit object
        run: |
          echo "${{ toJson(github.event.head_commit) }}"
      - name: Extract version from file name
        id: version
        run: |
          export TAG=$(echo ${{github.event.head_commit.modified}} | sed -n 's/.*YTCR.v\([0-9]*\.[0-9]*\.[0-9]*\).gezel/\1/p')
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Create or update tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN }}
          tag: ${{ env.TAG }}
          message: ${{ env.TAG }}
          release_branch: main
      - uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag.outputs.tag }}
          artifacts: "streamerbot/*.gezel"
          bodyFile: "streamerbot/README.md"
          generateReleaseNotes: true
          makeLatest: true